### ISSUE TITLE
subtitles not showing

### ISSUE THREAD

**Issue by vladimir12332** [cguZZman/plugin.onedrive#17] opened 2018-11-17 20:39 UTC
on various files, on android and PC addon doesn't show subtitles named same as video file.
1234.mkv and 1234.srt in same folder on OneDrive account.

Here is log file:
https://paste.kodi.tv/siroleyuta.kodi

**Comment by vladimir12332** [comment] 2018-11-17 20:41
on various files, on android and PC addon doesn't show subtitles named same as video file.
1234.mkv and 1234.srt in same folder on OneDrive account.

Here is log file:
`https://paste.kodi.tv/siroleyuta.kodi`

**Comment by vladimir12332** [comment] 2018-11-29 10:14
on various files, on android and PC addon doesn't show subtitles named same as video file.
1234.mkv and 1234.srt in same folder on OneDrive account.

Here is log file:
https://paste.kodi.tv/siroleyuta.kodi

**Comment by cguZZman** [comment] 2018-11-29 16:21
Thanks for the report and file.
Just reviewed your log file and the name of your video and subtitle files are correctly named. Looks like it's an issue with business drives only because in my personal drive it's working fine.
I'll research more about it.

**Comment by vladimir12332** [comment] 2018-12-23 11:43
any progress?

**Comment by alolgrijander** [comment] 2019-01-21 09:42
Dear Carlos!

Thanks for the add-on!

It works perfectly with subs included in .mkv, but unfortunately I am having the same issue as Vladimir is mentioning.
I tested 2 different personal accounts, and same result.
I tried .mkv, .mp4 and .avi, and same result.
I tried .srt, .sub, .txt, and same result.
I tried Kodi in 2 different devices, and same result.

When add-on is accessing the folders, it properly reads all files (subs included) in top right message.
But then then are not displayed, nor accessible.

Thanks in advance for you job!

**Comment by alolgrijander** [comment] 2019-01-22 11:13
Hi again!

Adding LOGs and pics.
![deadset_1](https://user-images.githubusercontent.com/46888346/51531952-25f38500-1e3f-11e9-874a-8092f0038008.png)
![deadset_2](https://user-images.githubusercontent.com/46888346/51531953-25f38500-1e3f-11e9-9611-a3d0b133ddb7.png)
![luther_1](https://user-images.githubusercontent.com/46888346/51531955-25f38500-1e3f-11e9-9ecb-451d0bf6bb05.png)
![luther_2](https://user-images.githubusercontent.com/46888346/51531956-25f38500-1e3f-11e9-8940-3362df302c5c.png)

[kodi.log](https://github.com/cguZZman/plugin.onedrive/files/2782490/kodi.log)

Thanks!

**Comment by cblogins** [comment] 2019-05-09 12:43
Hey guys, I experienced the same and the file encoding of the .srt was an issue for me. If the file was encoded anything other than UTF-8, the subtitles were not showing.
After I changed the encoding with notepad++ for example to UTF-8, uploaded the new file, waited a bit and then tried again, the subtitles were showing. Don't ask me why or if that was the actual root cause, that's just what I experienced :P

Have a look at how your .srt files are encoded.

Cheers

**Comment by arturximenes** [comment] 2019-12-12 20:32
I have this same problem **today**

**Comment by arturximenes** [comment] 2019-12-12 21:12
I have this problem to this day, I did as it was mentioned above and still does not work.

**Comment by cguZZman** [comment] 2020-10-11 02:46
should be fixed in latest version. test again and create a new ticket if the problem persists

**Closed by cguZZman** 2020-10-11 02:46 UTC
Labels: bug
