### ISSUE TITLE
Error message Unknown error: u '\ xdf' Please try again. What can I do ?

### ISSUE THREAD

**Issue by Collo1975** [cguZZman/plugin.onedrive#15] opened 2018-07-10 00:26 UTC
I can not watch some movies. Here the Logfile : https://paste.kodi.tv/gifiyigaki. Here a Picture : 
![20180710_005921](https://user-images.githubusercontent.com/41028730/42482550-72937f60-83e8-11e8-899b-3f41a476aa6b.jpg)

Thanks !!

**Comment by thomasmaster** [comment] 2018-07-11 13:11
I have the same issues.

**Comment by Collo1975** [comment] 2018-07-11 13:52
@thomasmaster  Kommst Du aus Deutschland ?

**Comment by cguZZman** [comment] 2018-07-11 14:00
The issue is fixed in my repository. https://github.com/cguZZman/repository.plugins
You can install my repository or wait for the update on the kodi repository.

**Closed by cguZZman** 2018-07-11 14:00 UTC

**Comment by Collo1975** [comment] 2018-07-11 20:15
Many thanks !!! It worked and the Movies are up and running again.
